using System.Drawing;
using System.Windows.Forms;

namespace RentXpress.Forms
{
    partial class VehicleDetailForm
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pnlMain;
        private Panel imgPanel;
        private Label imgLabel;
        private Label lblTagsHeader;
        private Label lblDescHeader;
        private Panel sep;
        private Label lblOwnerHeader;
        private Label lblName;
        private Label lblType;
        private Label lblPrice;
        private Label lblRating;
        private Label lblSeats;
        private Label lblFuel;
        private Label lblTrans;
        private Label lblStatus;
        private Label lblDescription;
        private Label lblOwnerName;
        private Label lblOwnerEmail;
        private Label lblOwnerPhone;
        private FlowLayoutPanel flpTags;
        private PictureBox picVehicle;
        private Button btnInquiry;
        private Button btnClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.pnlMain = new Panel();
            this.imgPanel = new Panel();
            this.imgLabel = new Label();
            this.picVehicle = new PictureBox();
            this.lblTagsHeader = new Label();
            this.lblDescHeader = new Label();
            this.sep = new Panel();
            this.lblOwnerHeader = new Label();
            this.lblName = new Label();
            this.lblType = new Label();
            this.lblPrice = new Label();
            this.lblRating = new Label();
            this.lblSeats = new Label();
            this.lblFuel = new Label();
            this.lblTrans = new Label();
            this.lblStatus = new Label();
            this.flpTags = new FlowLayoutPanel();
            this.lblDescription = new Label();
            this.lblOwnerName = new Label();
            this.lblOwnerEmail = new Label();
            this.lblOwnerPhone = new Label();
            this.btnInquiry = new Button();
            this.btnClose = new Button();
            this.pnlMain.SuspendLayout();
            this.imgPanel.SuspendLayout();
            this.SuspendLayout();
            this.pnlMain.BackColor = AppTheme.BgDark;
            this.pnlMain.Controls.Add(this.imgPanel);
            this.pnlMain.Controls.Add(this.lblName);
            this.pnlMain.Controls.Add(this.lblType);
            this.pnlMain.Controls.Add(this.lblPrice);
            this.pnlMain.Controls.Add(this.lblRating);
            this.pnlMain.Controls.Add(this.lblSeats);
            this.pnlMain.Controls.Add(this.lblFuel);
            this.pnlMain.Controls.Add(this.lblTrans);
            this.pnlMain.Controls.Add(this.lblStatus);
            this.pnlMain.Controls.Add(this.lblTagsHeader);
            this.pnlMain.Controls.Add(this.flpTags);
            this.pnlMain.Controls.Add(this.lblDescHeader);
            this.pnlMain.Controls.Add(this.lblDescription);
            this.pnlMain.Controls.Add(this.sep);
            this.pnlMain.Controls.Add(this.lblOwnerHeader);
            this.pnlMain.Controls.Add(this.lblOwnerName);
            this.pnlMain.Controls.Add(this.lblOwnerEmail);
            this.pnlMain.Controls.Add(this.lblOwnerPhone);
            this.pnlMain.Controls.Add(this.btnInquiry);
            this.pnlMain.Controls.Add(this.btnClose);
            this.pnlMain.Dock = DockStyle.Fill;
            this.pnlMain.Location = new Point(0, 0);
            this.pnlMain.Padding = new Padding(30);
            this.pnlMain.Size = new Size(680, 580);
            this.imgPanel.BackColor = Color.FromArgb(50, 50, 50);
            this.imgPanel.Controls.Add(this.picVehicle);
            this.imgPanel.Controls.Add(this.imgLabel);
            this.imgPanel.Location = new Point(30, 30);
            this.imgPanel.Name = "imgPanel";
            this.imgPanel.Size = new Size(280, 180);
            this.picVehicle.BackColor = Color.FromArgb(50, 50, 50);
            this.picVehicle.Dock = DockStyle.Fill;
            this.picVehicle.Name = "picVehicle";
            this.picVehicle.SizeMode = PictureBoxSizeMode.Zoom;
            this.picVehicle.Visible = false;
            this.imgLabel.AutoSize = true;
            this.imgLabel.Font = new Font("Segoe UI", 40F, FontStyle.Bold);
            this.imgLabel.ForeColor = AppTheme.TextSecondary;
            this.imgLabel.Location = new Point(105, 55);
            this.imgLabel.Name = "imgLabel";
            this.imgLabel.Text = "R";
            this.lblName.AutoSize = true;
            this.lblName.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblName.ForeColor = AppTheme.TextPrimary;
            this.lblName.Location = new Point(330, 30);
            this.lblName.Name = "lblName";
            this.lblName.Text = "Vehicle Name";
            this.lblType.AutoSize = true;
            this.lblType.Font = AppTheme.FontBody;
            this.lblType.ForeColor = AppTheme.TextSecondary;
            this.lblType.Location = new Point(330, 62);
            this.lblType.Name = "lblType";
            this.lblType.Text = "Type";
            this.lblPrice.AutoSize = true;
            this.lblPrice.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            this.lblPrice.ForeColor = AppTheme.Accent;
            this.lblPrice.Location = new Point(330, 90);
            this.lblPrice.Name = "lblPrice";
            this.lblPrice.Text = "Price";
            this.lblRating.AutoSize = true;
            this.lblRating.Font = AppTheme.FontBody;
            this.lblRating.ForeColor = AppTheme.StarColor;
            this.lblRating.Location = new Point(330, 126);
            this.lblRating.Name = "lblRating";
            this.lblRating.Text = "Rating";
            this.lblSeats.AutoSize = true;
            this.lblSeats.Font = AppTheme.FontBody;
            this.lblSeats.ForeColor = AppTheme.TextSecondary;
            this.lblSeats.Location = new Point(330, 154);
            this.lblSeats.Name = "lblSeats";
            this.lblSeats.Text = "Seats";
            this.lblFuel.AutoSize = true;
            this.lblFuel.Font = AppTheme.FontBody;
            this.lblFuel.ForeColor = AppTheme.TextSecondary;
            this.lblFuel.Location = new Point(330, 176);
            this.lblFuel.Name = "lblFuel";
            this.lblFuel.Text = "Fuel";
            this.lblTrans.AutoSize = true;
            this.lblTrans.Font = AppTheme.FontBody;
            this.lblTrans.ForeColor = AppTheme.TextSecondary;
            this.lblTrans.Location = new Point(430, 176);
            this.lblTrans.Name = "lblTrans";
            this.lblTrans.Text = "Transmission";
            this.lblStatus.AutoSize = true;
            this.lblStatus.Font = AppTheme.FontBody;
            this.lblStatus.ForeColor = AppTheme.Accent;
            this.lblStatus.Location = new Point(330, 198);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Text = "Status";
            this.lblTagsHeader.AutoSize = true;
            this.lblTagsHeader.Font = AppTheme.FontBody;
            this.lblTagsHeader.ForeColor = AppTheme.TextPrimary;
            this.lblTagsHeader.Location = new Point(30, 230);
            this.lblTagsHeader.Name = "lblTagsHeader";
            this.lblTagsHeader.Text = "Tags";
            this.flpTags.BackColor = Color.Transparent;
            this.flpTags.FlowDirection = FlowDirection.LeftToRight;
            this.flpTags.Location = new Point(30, 254);
            this.flpTags.Name = "flpTags";
            this.flpTags.Size = new Size(600, 38);
            this.lblDescHeader.AutoSize = true;
            this.lblDescHeader.Font = AppTheme.FontBody;
            this.lblDescHeader.ForeColor = AppTheme.TextPrimary;
            this.lblDescHeader.Location = new Point(30, 304);
            this.lblDescHeader.Name = "lblDescHeader";
            this.lblDescHeader.Text = "Description";
            this.lblDescription.Font = AppTheme.FontBody;
            this.lblDescription.ForeColor = AppTheme.TextSecondary;
            this.lblDescription.Location = new Point(30, 328);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new Size(600, 60);
            this.lblDescription.Text = "Description";
            this.sep.BackColor = AppTheme.BorderColor;
            this.sep.Location = new Point(30, 402);
            this.sep.Name = "sep";
            this.sep.Size = new Size(600, 1);
            this.lblOwnerHeader.AutoSize = true;
            this.lblOwnerHeader.Font = AppTheme.FontH2;
            this.lblOwnerHeader.ForeColor = AppTheme.TextPrimary;
            this.lblOwnerHeader.Location = new Point(30, 420);
            this.lblOwnerHeader.Name = "lblOwnerHeader";
            this.lblOwnerHeader.Text = "Owner Information";
            this.lblOwnerName.AutoSize = true;
            this.lblOwnerName.Font = AppTheme.FontBody;
            this.lblOwnerName.ForeColor = AppTheme.TextSecondary;
            this.lblOwnerName.Location = new Point(30, 452);
            this.lblOwnerName.Name = "lblOwnerName";
            this.lblOwnerName.Text = "Owner";
            this.lblOwnerEmail.AutoSize = true;
            this.lblOwnerEmail.Font = AppTheme.FontBody;
            this.lblOwnerEmail.ForeColor = AppTheme.TextSecondary;
            this.lblOwnerEmail.Location = new Point(30, 474);
            this.lblOwnerEmail.Name = "lblOwnerEmail";
            this.lblOwnerEmail.Text = "Email";
            this.lblOwnerPhone.AutoSize = true;
            this.lblOwnerPhone.Font = AppTheme.FontBody;
            this.lblOwnerPhone.ForeColor = AppTheme.TextSecondary;
            this.lblOwnerPhone.Location = new Point(30, 496);
            this.lblOwnerPhone.Name = "lblOwnerPhone";
            this.lblOwnerPhone.Text = "Phone";
            this.btnInquiry.BackColor = AppTheme.Accent;
            this.btnInquiry.FlatAppearance.BorderSize = 0;
            this.btnInquiry.FlatStyle = FlatStyle.Flat;
            this.btnInquiry.Font = AppTheme.FontButton;
            this.btnInquiry.ForeColor = AppTheme.TextPrimary;
            this.btnInquiry.Location = new Point(30, 525);
            this.btnInquiry.Name = "btnInquiry";
            this.btnInquiry.Size = new Size(180, 40);
            this.btnInquiry.Text = "Send Inquiry";
            this.btnInquiry.UseVisualStyleBackColor = false;
            this.btnInquiry.Click += new System.EventHandler(this.btnInquiry_Click);
            this.btnClose.BackColor = AppTheme.BgInput;
            this.btnClose.FlatAppearance.BorderColor = AppTheme.BorderColor;
            this.btnClose.FlatStyle = FlatStyle.Flat;
            this.btnClose.Font = AppTheme.FontButton;
            this.btnClose.ForeColor = AppTheme.TextPrimary;
            this.btnClose.Location = new Point(520, 525);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new Size(100, 40);
            this.btnClose.Text = "Close";
            this.btnClose.UseVisualStyleBackColor = false;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            this.AutoScaleDimensions = new SizeF(96F, 96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.BackColor = AppTheme.BgDark;
            this.ClientSize = new Size(680, 580);
            this.Controls.Add(this.pnlMain);
            this.FormBorderStyle = FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.Name = "VehicleDetailForm";
            this.StartPosition = FormStartPosition.CenterParent;
            this.Text = "RentXpress - Vehicle";
            this.imgPanel.ResumeLayout(false);
            this.imgPanel.PerformLayout();
            this.pnlMain.ResumeLayout(false);
            this.pnlMain.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}




