using System.Drawing;
using System.Windows.Forms;

namespace RentXpress.Forms
{
    partial class VehicleDetailForm
    {
        private System.ComponentModel.IContainer components = null;
        private Label lblName;
        private Label lblType;
        private Label lblPrice;
        private Label lblRating;
        private Label lblSeats;
        private Label lblFuel;
        private Label lblTrans;
        private Label lblStatus;
        private Label lblDescription;
        private Label lblOwnerName;
        private Label lblOwnerEmail;
        private Label lblOwnerPhone;
        private FlowLayoutPanel flpTags;
        private PictureBox picVehicle;
        private Button btnInquiry;
        private Button btnClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            Panel pnlMain = new Panel();
            Panel imgPanel = new Panel();
            Label imgLabel = new Label();
            this.picVehicle = new PictureBox();
            Label lblTagsHeader = new Label();
            Label lblDescHeader = new Label();
            Panel sep = new Panel();
            Label lblOwnerHeader = new Label();
            this.lblName = new Label();
            this.lblType = new Label();
            this.lblPrice = new Label();
            this.lblRating = new Label();
            this.lblSeats = new Label();
            this.lblFuel = new Label();
            this.lblTrans = new Label();
            this.lblStatus = new Label();
            this.flpTags = new FlowLayoutPanel();
            this.lblDescription = new Label();
            this.lblOwnerName = new Label();
            this.lblOwnerEmail = new Label();
            this.lblOwnerPhone = new Label();
            this.btnInquiry = new Button();
            this.btnClose = new Button();
            pnlMain.SuspendLayout();
            imgPanel.SuspendLayout();
            this.SuspendLayout();
            pnlMain.BackColor = AppTheme.BgDark;
            pnlMain.Controls.Add(imgPanel);
            pnlMain.Controls.Add(this.lblName);
            pnlMain.Controls.Add(this.lblType);
            pnlMain.Controls.Add(this.lblPrice);
            pnlMain.Controls.Add(this.lblRating);
            pnlMain.Controls.Add(this.lblSeats);
            pnlMain.Controls.Add(this.lblFuel);
            pnlMain.Controls.Add(this.lblTrans);
            pnlMain.Controls.Add(this.lblStatus);
            pnlMain.Controls.Add(lblTagsHeader);
            pnlMain.Controls.Add(this.flpTags);
            pnlMain.Controls.Add(lblDescHeader);
            pnlMain.Controls.Add(this.lblDescription);
            pnlMain.Controls.Add(sep);
            pnlMain.Controls.Add(lblOwnerHeader);
            pnlMain.Controls.Add(this.lblOwnerName);
            pnlMain.Controls.Add(this.lblOwnerEmail);
            pnlMain.Controls.Add(this.lblOwnerPhone);
            pnlMain.Controls.Add(this.btnInquiry);
            pnlMain.Controls.Add(this.btnClose);
            pnlMain.Dock = DockStyle.Fill;
            pnlMain.Location = new Point(0, 0);
            pnlMain.Padding = new Padding(30);
            pnlMain.Size = new Size(680, 580);
            imgPanel.BackColor = Color.FromArgb(50, 50, 50);
            imgPanel.Controls.Add(this.picVehicle);
            imgPanel.Controls.Add(imgLabel);
            imgPanel.Location = new Point(30, 30);
            imgPanel.Name = "imgPanel";
            imgPanel.Size = new Size(280, 180);
            this.picVehicle.BackColor = Color.FromArgb(50, 50, 50);
            this.picVehicle.Dock = DockStyle.Fill;
            this.picVehicle.Name = "picVehicle";
            this.picVehicle.SizeMode = PictureBoxSizeMode.Zoom;
            this.picVehicle.Visible = false;
            imgLabel.AutoSize = true;
            imgLabel.Font = new Font("Segoe UI", 40F, FontStyle.Bold);
            imgLabel.ForeColor = AppTheme.TextSecondary;
            imgLabel.Location = new Point(105, 55);
            imgLabel.Text = "R";
            this.lblName.AutoSize = true;
            this.lblName.Font = new Font("Segoe UI", 16F, FontStyle.Bold);
            this.lblName.ForeColor = AppTheme.TextPrimary;
            this.lblName.Location = new Point(330, 30);
            this.lblName.Name = "lblName";
            this.lblName.Text = "Vehicle Name";
            this.lblType.AutoSize = true;
            this.lblType.Font = AppTheme.FontBody;
            this.lblType.ForeColor = AppTheme.TextSecondary;
            this.lblType.Location = new Point(330, 62);
            this.lblType.Name = "lblType";
            this.lblType.Text = "Type";
            this.lblPrice.AutoSize = true;
            this.lblPrice.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            this.lblPrice.ForeColor = AppTheme.Accent;
            this.lblPrice.Location = new Point(330, 90);
            this.lblPrice.Name = "lblPrice";
            this.lblPrice.Text = "Price";
            this.lblRating.AutoSize = true;
            this.lblRating.Font = AppTheme.FontBody;
            this.lblRating.ForeColor = AppTheme.StarColor;
            this.lblRating.Location = new Point(330, 126);
            this.lblRating.Name = "lblRating";
            this.lblRating.Text = "Rating";
            this.lblSeats.AutoSize = true;
            this.lblSeats.Font = AppTheme.FontBody;
            this.lblSeats.ForeColor = AppTheme.TextSecondary;
            this.lblSeats.Location = new Point(330, 154);
            this.lblSeats.Name = "lblSeats";
            this.lblSeats.Text = "Seats";
            this.lblFuel.AutoSize = true;
            this.lblFuel.Font = AppTheme.FontBody;
            this.lblFuel.ForeColor = AppTheme.TextSecondary;
            this.lblFuel.Location = new Point(330, 176);
            this.lblFuel.Name = "lblFuel";
            this.lblFuel.Text = "Fuel";
            this.lblTrans.AutoSize = true;
            this.lblTrans.Font = AppTheme.FontBody;
            this.lblTrans.ForeColor = AppTheme.TextSecondary;
            this.lblTrans.Location = new Point(430, 176);
            this.lblTrans.Name = "lblTrans";
            this.lblTrans.Text = "Transmission";
            this.lblStatus.AutoSize = true;
            this.lblStatus.Font = AppTheme.FontBody;
            this.lblStatus.ForeColor = AppTheme.Accent;
            this.lblStatus.Location = new Point(330, 198);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Text = "Status";
            lblTagsHeader.AutoSize = true;
            lblTagsHeader.Font = AppTheme.FontBody;
            lblTagsHeader.ForeColor = AppTheme.TextPrimary;
            lblTagsHeader.Location = new Point(30, 230);
            lblTagsHeader.Text = "Tags";
            this.flpTags.BackColor = Color.Transparent;
            this.flpTags.FlowDirection = FlowDirection.LeftToRight;
            this.flpTags.Location = new Point(30, 254);
            this.flpTags.Name = "flpTags";
            this.flpTags.Size = new Size(600, 38);
            lblDescHeader.AutoSize = true;
            lblDescHeader.Font = AppTheme.FontBody;
            lblDescHeader.ForeColor = AppTheme.TextPrimary;
            lblDescHeader.Location = new Point(30, 304);
            lblDescHeader.Text = "Description";
            this.lblDescription.Font = AppTheme.FontBody;
            this.lblDescription.ForeColor = AppTheme.TextSecondary;
            this.lblDescription.Location = new Point(30, 328);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new Size(600, 60);
            this.lblDescription.Text = "Description";
            sep.BackColor = AppTheme.BorderColor;
            sep.Location = new Point(30, 402);
            sep.Size = new Size(600, 1);
            lblOwnerHeader.AutoSize = true;
            lblOwnerHeader.Font = AppTheme.FontH2;
            lblOwnerHeader.ForeColor = AppTheme.TextPrimary;
            lblOwnerHeader.Location = new Point(30, 420);
            lblOwnerHeader.Text = "Owner Information";
            this.lblOwnerName.AutoSize = true;
            this.lblOwnerName.Font = AppTheme.FontBody;
            this.lblOwnerName.ForeColor = AppTheme.TextSecondary;
            this.lblOwnerName.Location = new Point(30, 452);
            this.lblOwnerName.Name = "lblOwnerName";
            this.lblOwnerName.Text = "Owner";
            this.lblOwnerEmail.AutoSize = true;
            this.lblOwnerEmail.Font = AppTheme.FontBody;
            this.lblOwnerEmail.ForeColor = AppTheme.TextSecondary;
            this.lblOwnerEmail.Location = new Point(30, 474);
            this.lblOwnerEmail.Name = "lblOwnerEmail";
            this.lblOwnerEmail.Text = "Email";
            this.lblOwnerPhone.AutoSize = true;
            this.lblOwnerPhone.Font = AppTheme.FontBody;
            this.lblOwnerPhone.ForeColor = AppTheme.TextSecondary;
            this.lblOwnerPhone.Location = new Point(30, 496);
            this.lblOwnerPhone.Name = "lblOwnerPhone";
            this.lblOwnerPhone.Text = "Phone";
            this.btnInquiry.BackColor = AppTheme.Accent;
            this.btnInquiry.FlatAppearance.BorderSize = 0;
            this.btnInquiry.FlatStyle = FlatStyle.Flat;
            this.btnInquiry.Font = AppTheme.FontButton;
            this.btnInquiry.ForeColor = AppTheme.TextPrimary;
            this.btnInquiry.Location = new Point(30, 525);
            this.btnInquiry.Name = "btnInquiry";
            this.btnInquiry.Size = new Size(180, 40);
            this.btnInquiry.Text = "Send Inquiry";
            this.btnInquiry.UseVisualStyleBackColor = false;
            this.btnInquiry.Click += new System.EventHandler(this.btnInquiry_Click);
            this.btnClose.BackColor = AppTheme.BgInput;
            this.btnClose.FlatAppearance.BorderColor = AppTheme.BorderColor;
            this.btnClose.FlatStyle = FlatStyle.Flat;
            this.btnClose.Font = AppTheme.FontButton;
            this.btnClose.ForeColor = AppTheme.TextPrimary;
            this.btnClose.Location = new Point(520, 525);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new Size(100, 40);
            this.btnClose.Text = "Close";
            this.btnClose.UseVisualStyleBackColor = false;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            this.AutoScaleDimensions = new SizeF(96F, 96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.BackColor = AppTheme.BgDark;
            this.ClientSize = new Size(680, 580);
            this.Controls.Add(pnlMain);
            this.FormBorderStyle = FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.Name = "VehicleDetailForm";
            this.StartPosition = FormStartPosition.CenterParent;
            this.Text = "RentXpress - Vehicle";
            imgPanel.ResumeLayout(false);
            imgPanel.PerformLayout();
            pnlMain.ResumeLayout(false);
            pnlMain.PerformLayout();
            this.ResumeLayout(false);
        }
    }
}




